var searchData=
[
  ['of_20channels_0',['ADC instance - Sampling time common to a group of channels',['../group___a_d_c___h_a_l___e_c___s_a_m_p_l_i_n_g_t_i_m_e___c_o_m_m_o_n.html',1,'']]],
  ['of_20unitary_20conversion_20or_20sequence_20conversions_1',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_2',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_3',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['on_20conversion_20data_4',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['on_20gpio_5',['Fast mode Plus on GPIO',['../group___s_y_s_c_f_g___fast_mode_plus___g_p_i_o.html',1,'']]],
  ['on_20standby_6',['On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['on_20stop_7',['On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['one_20pulse_20functions_8',['One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group___t_i_m___exported___functions___group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_9',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_10',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_11',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operation_20functions_12',['operation functions',['../group___e_x_t_i___exported___functions___group2.html',1,'IO operation functions'],['../group___g_p_i_o___exported___functions___group2.html',1,'IO operation functions']]],
  ['option_20bit_13',['FLASH Option Bytes User nBOOT0 option bit',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t0.html',1,'']]],
  ['option_20bytes_20read_20protection_14',['FLASH Option Bytes Read Protection',['../group___f_l_a_s_h___o_b___read___protection.html',1,'']]],
  ['option_20bytes_20type_15',['FLASH Option Bytes Type',['../group___f_l_a_s_h___o_b___type.html',1,'']]],
  ['option_20bytes_20user_20boot0_20selection_16',['FLASH Option Bytes User Boot0 Selection',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t___s_e_l.html',1,'']]],
  ['option_20bytes_20user_20boot1_20type_17',['FLASH Option Bytes User BOOT1 Type',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t1.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20standby_18',['FLASH Option Bytes User IWDG Mode On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20stop_19',['FLASH Option Bytes User IWDG Mode On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20type_20',['FLASH Option Bytes User IWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_w.html',1,'']]],
  ['option_20bytes_20user_20nboot0_20option_20bit_21',['FLASH Option Bytes User nBOOT0 option bit',['../group___f_l_a_s_h___o_b___u_s_e_r__n_b_o_o_t0.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20standby_22',['FLASH Option Bytes User Reset On Standby',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20stop_23',['FLASH Option Bytes User Reset On Stop',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20bytes_20user_20sram_20parity_24',['FLASH Option Bytes User SRAM parity',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m___p_a_r_i_t_y.html',1,'']]],
  ['option_20bytes_20user_20type_25',['FLASH Option Bytes User Type',['../group___f_l_a_s_h___o_b___u_s_e_r___type.html',1,'']]],
  ['option_20bytes_20user_20wwdg_20type_26',['FLASH Option Bytes User WWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___w_w_d_g___s_w.html',1,'']]],
  ['or_203_27',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['or_20disabled_20status_28',['or Disabled Status',['../group___r_c_c___a_h_b___peripheral___clock___enabled___disabled___status.html',1,'AHB Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b___clock___sleep___enabled___disabled___status.html',1,'AHB Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___enabled___disabled___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___clock___sleep___enabled___disabled___status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___enabled___disabled___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___clock___sleep___enabled___disabled___status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group___r_c_c___i_o_p_o_r_t___clock___enabled___disabled___status.html',1,'IOPORT Clock Enabled or Disabled Status'],['../group___r_c_c___i_o_p_o_r_t___clock___sleep___enabled___disabled___status.html',1,'IOPORT Clock Sleep Enabled or Disabled Status']]],
  ['or_20sequence_20conversions_29',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['oscillator_20type_30',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_31',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_32',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['output_33',['PLL Clock Output',['../group___r_c_c___p_l_l___clock___output.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_34',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_35',['Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_36',['Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_37',['Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_38',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20enable_39',['TIM Automatic Output Enable',['../group___t_i_m___a_o_e___bit___set___reset.html',1,'']]],
  ['output_20fast_20state_40',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['output_20polarity_20selection_41',['IR output polarity selection',['../group___h_a_l___i_r___p_o_l___s_e_l.html',1,'']]],
  ['overrun_20behavior_20on_20conversion_20data_42',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['oversampling_20data_20shift_43',['Oversampling - Data shift',['../group___a_d_c___h_a_l___e_c___o_v_s___s_h_i_f_t.html',1,'']]],
  ['oversampling_20discontinuous_20mode_44',['Oversampling - Discontinuous mode',['../group___a_d_c___h_a_l___e_c___o_v_s___d_i_s_c_o_n_t___m_o_d_e.html',1,'']]],
  ['oversampling_20ratio_45',['Oversampling - Ratio',['../group___a_d_c___h_a_l___e_c___o_v_s___r_a_t_i_o.html',1,'']]]
];
